version: "3.4"

services:

  proxy:
    container_name: json2resume-nginx-proxy
    image: nginxproxy/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    restart: unless-stopped

  webserver:
    container_name: json2resume-nginx-server
    image: nginx:alpine
    working_dir: /application
    environment:
      - VIRTUAL_HOST=localhost
    volumes:
      - ./:/application:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    container_name: json2resume-php-fpm
    build:
      args:
        composer_user: toor
        user: www-data
        group: www-data
        uid: 1000
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      target: test
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ./:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini